const JenisTransaksi = [
  {
    key: "laku-pandai",
    value: "disabled",
    label: "Laku Pandai",
    isDisabled: true,
  },
  {
    key: 1,
    value: 1,
    label: "Cash-in & Out",
    isDisabled: false,
  },
  {
    key: 2,
    value: 2,
    label: "Report",
    isDisabled: false,
  },
  {
    key: 3,
    value: 3,
    label: "Setoran Uang",
    isDisabled: false,
  },
  {
    key: 4,
    value: 4,
    label: "Tarik Tunai",
    isDisabled: false,
  },
  {
    key: 5,
    value: 5,
    label: "Isi Ulang Pulsa",
    isDisabled: false,
  },
  {
    key: 6,
    value: 6,
    label: "Belanja Merchant",
    isDisabled: false,
  },
  {
    key: "tunai",
    value: "disabled",
    label: "Tunai",
    isDisabled: true,
  },
  {
    key: 7,
    value: 7,
    label: "Setoran Pinjaman",
    isDisabled: false,
  },
  {
    key: 8,
    value: 8,
    label: "Setoran Simpanan",
    isDisabled: false,
  },
  {
    key: 9,
    value: 9,
    label: "Tarik Tunai",
    isDisabled: false,
  },
  {
    key: "mini-atm-bri",
    value: "Mini ATM BRI",
    label: "Mini ATM BRI",
    isDisabled: true,
  },
  {
    key: 10,
    value: 10,
    label: "Registrasi Mobile Banking",
    isDisabled: false,
  },
  {
    key: 11,
    value: 11,
    label: "Registrasi Internet Banking",
    isDisabled: false,
  },
  {
    key: 12,
    value: 12,
    label: "Informasi Rekening",
    isDisabled: false,
  },
  {
    key: 13,
    value: 13,
    label: "Transfer Pembayaran",
    isDisabled: false,
  },
  {
    key: 14,
    value: 14,
    label: "Isi Ulang Pulsa",
    isDisabled: false,
  },
  {
    key: 15,
    value: 15,
    label: "Setor Pasti",
    isDisabled: false,
  },
]
export default JenisTransaksi
